### ISSUE TITLE
Found input variables without list of list.

### ISSUE THREAD

**Issue by jackragless** [ibatra/BERT-Keyword-Extractor#17]
Running the repository without any modifications and getting the following error? Does anyone know how to fix this?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-22-934434e5a337> in <module>
     58     pred_tags = [tags_vals[p_i] for p in predictions for p_i in p]
     59     valid_tags = [tags_vals[l_ii] for l in true_labels for l_i in l for l_ii in l_i]
---> 60     print("F1-Score: {}".format(f1_score(pred_tags, valid_tags)))

~/miniconda3/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py in f1_score(y_true, y_pred, average, suffix, mode, sample_weight, zero_division, scheme)
    357                                                         suffix=suffix)
    358     else:
--> 359         _, _, f, _ = precision_recall_fscore_support(y_true, y_pred,
    360                                                      average=average,
    361                                                      warn_for=('f-score',),

~/miniconda3/lib/python3.8/site-packages/seqeval/metrics/sequence_labeling.py in precision_recall_fscore_support(y_true, y_pred, average, warn_for, beta, sample_weight, zero_division, suffix)
    128         return pred_sum, tp_sum, true_sum
    129 
--> 130     precision, recall, f_score, true_sum = _precision_recall_fscore_support(
    131         y_true, y_pred,
    132         average=average,

~/miniconda3/lib/python3.8/site-packages/seqeval/metrics/v1.py in _precision_recall_fscore_support(y_true, y_pred, average, warn_for, beta, sample_weight, zero_division, scheme, suffix, extract_tp_actual_correct)
    120         raise ValueError('average has to be one of {}'.format(average_options))
    121 
--> 122     check_consistent_length(y_true, y_pred)
    123 
    124     pred_sum, tp_sum, true_sum = extract_tp_actual_correct(y_true, y_pred, suffix, scheme)

~/miniconda3/lib/python3.8/site-packages/seqeval/metrics/v1.py in check_consistent_length(y_true, y_pred)
     95     is_list = set(map(type, y_true)) | set(map(type, y_pred))
     96     if not is_list == {list}:
---> 97         raise TypeError('Found input variables without list of list.')
     98 
     99     if len(y_true) != len(y_pred) or len_true != len_pred:

TypeError: Found input variables without list of list.

**Comment by Xie-Minghui** [comment]
I encounted this problem too.
my code is as follows:
# -*- coding: utf-8 -*-
from seqeval.metrics import f1_score
from seqeval.metrics import precision_score
from seqeval.metrics import accuracy_score
from seqeval.metrics import recall_score
from seqeval.metrics import classification_report
 
y_true = ['O', 'O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'O', 'B-PER', 'I-PER']
y_pred = ['O', 'O', 'B-MISC', 'I-MISC', 'B-MISC', 'I-MISC', 'O', 'B-PER', 'I-PER']
 
print("accuary: ", accuracy_score(y_true, y_pred))
print("p: ", precision_score(y_true, y_pred))
print("r: ", recall_score(y_true, y_pred))
print("f1: ", f1_score(y_true, y_pred))
print("classification report: ")

As the error info said, I changed y_true and y_pred to "[['O', 'O', 'O', 'B-MISC', 'I-MISC', 'I-MISC', 'O', 'B-PER', 'I-PER']]", it worked

**Comment by jackragless** [comment]
Hey @mangonihao cheers for looking into this, I managed to figure out the issue quite a while ago. It's a bug in this repository related to to the F1-score calculation as I recall. Weirdly enough I found the best way to train your own keyword extraction model is just to use the NER pipeline from SimpleTransformers.

**Comment by humakilicunlu** [comment]
For this repository it was just a bug. I remove the control because y_pred and y_true lists have the same size.

**Comment by ahmadaii** [comment]
I have modified the solution and it is working perfectly.

**Comment by ksdihgfmata** [comment]
@humakilicunlu : Could you please explain how to do it?  I have the same problem.
