### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by pbabvey** [ibatra/BERT-Keyword-Extractor#3]
I get some errors while running the code, some packages are not imported. There are some other error that may be fixed but I did not go through the details. Ishaan, would you update your code?

**Comment by ibatra** [comment]
could you provide a list of packages so i can update the code?

**Comment by ShivanshuPurohit** [comment]
numpy isn't imported for `keyword_extraction.py` and seqeval is posing problems with the f1 score
