### ISSUE TITLE
More than one Keyword

### ISSUE THREAD

**Issue by thanish** [ibatra/BERT-Keyword-Extractor#6]
I have a requirement were I need to extract more than one keyword from the sentence. Is it possible to do with just passing the text of interest once?
Example:
Input text:  "I don't like this coffee because it's too sweet after having it for few days I don't like it anymore" 
Output keywords: "too sweet" and "don't like it".

**Comment by cabhijith** [comment]
@thanish Were you able to that? Would love if you could share it!

**Comment by thanish** [comment]
@cabhijith : Yes I was able to achieve it with a little modification. The main things lies in the labeling where you do a token by token match(between keyword token and sentence token) to create the labels for more than 1 keyword in the sentence dataset.

This is how my training and label data looked like 

Sentence : "I bought coffee and it is too sweet after having it for few days I do not like it anymore"
Keywords: ["too sweet" , "do not like it"]

Sentence Token: ["I", "bought", "coffee", "and",  "it", "is", "too", "sweet", "after", "having", "it", "for", "few", "days", "I", "do", "not", "like", "it", "anymore"]
Keyword Token : [["too", "sweet"] , ["do", "not", "like", "it"]]

labels: [0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,1,1,1,0]. 

I did not use 
tag2idx = {'B': 0, 'I': 1, 'O': 2}
tags_vals = ['B', 'I', 'O']

but I just changed it to my need as
tag2idx = {'O' : 0, 'I': 1}
tags_vals = ['O', 'I']

where 'I' is the keyword tokens and O is the non-keyword tokens

**Comment by cabhijith** [comment]
Ahh was thinking of something similar, thanks for the detailed response @thanish.

**Comment by PTTrazavi** [comment]
Some opinions here to discuss... 

For multiple keywords extraction, I think the original code (tags_vals = ['B', 'I', 'O']) is correct.
The original code can extract multiple keywords.
Removing 'B' doesn't seem right, because 'B' indicates the first token in a multi-token entity, and 'I' indicates one in the middle of a multi-token entity.
